### PR TITLE
add /api/getcity endpoint

### PR DESCRIPTION
**Pull request by apoorvsingal**
I am not quite sure if  /routes/apiRoutes.js is where those contents belong and if the endpoint should be called /getcity. Help pls

### CODE REVIEW

**Comment by Utkarshbhimte** [comment]
What is the objective of this API?

**Comment by SwarnimWalavalkar** [comment]
You can create a `meta.js` file in the routes directory and move these there...

**Review by SwarnimWalavalkar — APPROVED** [review]

**Review by SwarnimWalavalkar — CHANGES_REQUESTED** [review]
Move the `/getcity` route to `/routes/meta.js`
Suggestion to rename `getcity` to `checkcity` since the endpoint doesn't return a specfic resource...

**Comment by Utkarshbhimte** [comment]
@apoorvsingal @SwarnimWalavalkar why do we need this?

**Comment by rgxai** [comment]
> @apoorvsingal @SwarnimWalavalkar why do we need this?

@Utkarshbhimte for the whatsapp chatbot to validate the list of cities and return true or false if the user's prompt matches the list in our database. also, it converts and maps back Hindi inputs to English counterparts.

**Comment by Utkarshbhimte** [comment]
@rgxai I am not sure but the whatsapp bot will also interact with this server, right? Wouldn't creating a helper function here be more helpful?

**Review by SwarnimWalavalkar — APPROVED** [review]

**Pull request merged**
